inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  Exclude:
    - vendor/**
    - bin/**

Style/NumericLiteralPrefix:
  Enabled: true
  EnforcedOctalStyle: zero_only
